---
- name: Learn Ansible Vault
  hosts: unikraft

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Create application environment file
      ansible.builtin.copy:
        content: |
          DB_PASSWORD={{ db_password }}
          API_TOKEN={{ api_token }}
        dest: /opt/ansible-demo/app.env
        mode: "0600"

